name: Test workflow
on:
  push:
    branches: ['main']
jobs:
  test_docker:
    name: test docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: testbuild
        run: ls -la
