name: Test workflow
on:
  push:
    branches: ['master']
jobs:
  test_docker:
    name: test docker
    runs-on: ubuntu-latest
    steps:
      - uses: git@github.com:donne22/donne22.git
      - name: testbuild
        run: ls -la
